# Generated by Django 5.1.2 on 2024-10-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_profile_num_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='password',
            field=models.CharField(default='rh24', max_length=50),
        ),
    ]
